typography_spectrum: 0.4957447
color:
  lightness: 0.6723405
  brandStrength: 0
  saturation: 0.812766
  rhythmicContrast: 1
  brandColors:
    - '#100B0A'
    - '#849189'
    - '#FFFFEB'
    - '#FF92FF'
    - '#FFFA0E'
layout_spectrum: 0.3106383
name: Puzzlepanel
navigation:
  - name: Small Business Time Saver App
    url: www.puzzlepanel.com
    type: external
title: Amazing
description: Works
