layout_spectrum: 0.1021277
typography_spectrum: 0.4957447
color:
  lightness: 1
  brandStrength: 0
  saturation: 0.812766
  rhythmicContrast: 1
  brandColors:
    - '#100B0A'
    - '#849189'
    - '#FFFFEB'
    - '#FF92FF'
    - '#FFFA0E'
name: Puzzlepanel
